### ISSUE TITLE
Retrieving Passwords Suffix

### ISSUE THREAD

**Issue by kristenbeh** [GoogleCloudPlatform/citrix-on-gcp#1]
Running .\get-domain-admin-password.ps1 results in the following error message.  Trying to input prefix/suffix parameters does not work either. 

C:\Users\Unidesk\Documents\citrix-on-gcp-master\get-domain-admin-password.ps1 : Please specify a suffix and try again.
At line:1 char:1
+ .\get-domain-admin-password.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,get-domain-admin-password.ps1

**Comment by jeffallen-google** [comment]
Hi, thanks for your interest in citrix-on-gcp!

There are a few scripts in the repo (including the one you tried) which are designed to take action on existing deployments, namely:
- resize.ps1
- cleanup.ps1
- get-domain-admin-password.ps1
- get-domain-users.ps1

When these scripts start, they look within the specified Google Cloud project for a Deployment Manager deployment matching the name "citrix-on-gcp-suffix" where "suffix" is a 6-character alpha-numeric identifier.  Any matching deployments will be presented in a list for you to select the deployment to take action on.

Your error suggests the script can't find a deployment matching the name citrix-on-gcp-suffix.  Assuming deploy.ps1 has already been run to create that deployment, the most common cause of your error is specifying the wrong project.

All these scripts will use your gcloud default project and also allow you to override the default with a command-line parameter.

Can you verify which project you specified when you ran deploy.ps1?  Perhaps look for the citrix-on-gcp-suffix deployment in the Deployment Manager console:

https://console.cloud.google.com/dm/deployments

Once you identify the project, make sure you are running the get password script against that same project.  If necessary, you can set your default gcloud project with:

gcloud config set core/project YOUR_PROJECT_ID

Or, specify the project on the command-line, such as:

.\get-domain-admin-password.ps1 -Project YOUR_PROJECT_ID

Please try this out and let us know if you are still having issues.
